version: '3.1'

services:
  messenger:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messenger
    ports:
      - 5432:5432

  app:
    build: ./app
    restart: always
    image: app:latest
    ports:
      - 5000:5000
    depends_on:
      - messenger
    links:
      - "messenger:messenger"
